# -*- coding: utf-8 -*-
"""Finans Belgesi sabitleri — FAZ-FINANS-1C."""
from __future__ import annotations

KAYNAK_MODUL = 'FINANS_MERKEZI'

# Belge tipleri
BELGE_TIP_SATIS_SEVKIYAT = 'SATIS_SEVKIYAT'
BELGE_TIP_TAHSILAT = 'TAHSILAT'
BELGE_TIPLERI: tuple[str, ...] = (BELGE_TIP_SATIS_SEVKIYAT, BELGE_TIP_TAHSILAT)

# Kaynak tipleri (audit / idempotency — kolon migration 1C.1)
KAYNAK_TIP_SEVKIYAT = 'SEVKIYAT'
KAYNAK_TIP_TAHSILAT_KAYIT = 'TAHSILAT_KAYIT'

# Durumlar (MVP)
DURUM_BEKLIYOR = 'BEKLIYOR'
DURUM_EKSIK_BILGI = 'EKSIK_BILGI'
DURUM_INCELEMEDE = 'INCELEMEDE'
DURUM_DUZELTME_BEKLIYOR = 'DUZELTME_BEKLIYOR'
DURUM_ONAYLANDI = 'ONAYLANDI'
DURUM_POST_EDILDI = 'POST_EDILDI'
DURUM_REDDEDILDI = 'REDDEDILDI'
DURUM_KAPANDI = 'KAPANDI'

DURUMLAR: tuple[str, ...] = (
    DURUM_BEKLIYOR,
    DURUM_EKSIK_BILGI,
    DURUM_INCELEMEDE,
    DURUM_DUZELTME_BEKLIYOR,
    DURUM_ONAYLANDI,
    DURUM_POST_EDILDI,
    DURUM_REDDEDILDI,
    DURUM_KAPANDI,
)

DURUM_ETIKET = {
    DURUM_BEKLIYOR: 'Finans Bekliyor',
    DURUM_EKSIK_BILGI: 'Eksik Bilgi',
    DURUM_INCELEMEDE: 'İncelemede',
    DURUM_DUZELTME_BEKLIYOR: 'Düzeltme Bekliyor',
    DURUM_ONAYLANDI: 'Onaylandı',
    DURUM_POST_EDILDI: 'Post Edildi',
    DURUM_REDDEDILDI: 'Reddedildi',
    DURUM_KAPANDI: 'Kapandı',
}

# Geçerli durum geçişleri
DURUM_GECIS: dict[str, frozenset[str]] = {
    DURUM_BEKLIYOR: frozenset({DURUM_INCELEMEDE, DURUM_EKSIK_BILGI}),
    DURUM_EKSIK_BILGI: frozenset({DURUM_INCELEMEDE}),
    DURUM_INCELEMEDE: frozenset({DURUM_ONAYLANDI, DURUM_DUZELTME_BEKLIYOR, DURUM_REDDEDILDI}),
    DURUM_DUZELTME_BEKLIYOR: frozenset({DURUM_BEKLIYOR}),
    DURUM_ONAYLANDI: frozenset({DURUM_POST_EDILDI}),
    DURUM_POST_EDILDI: frozenset({DURUM_KAPANDI}),
    DURUM_REDDEDILDI: frozenset(),
    DURUM_KAPANDI: frozenset(),
}

# Audit olay tipleri
OLAY_BELGE_OLUSTURULDU = 'BELGE_OLUSTURULDU'
OLAY_INCELEMEYE_ALINDI = 'INCELEMEYE_ALINDI'
OLAY_DUZELTMEYE_GONDERILDI = 'DUZELTMEYE_GONDERILDI'
OLAY_ONAYLANDI = 'ONAYLANDI'
OLAY_POST_EDILDI = 'POST_EDILDI'
OLAY_POST_DRY_RUN = 'POST_DRY_RUN'
OLAY_REDDEDILDI = 'REDDEDILDI'
OLAY_KAPANDI = 'KAPANDI'

ONAYA_HAZIR_DURUMLAR = frozenset({DURUM_INCELEMEDE})

def idempotency_sevkiyat(sevkiyat_id: int) -> str:
    return f'{BELGE_TIP_SATIS_SEVKIYAT}:{KAYNAK_TIP_SEVKIYAT}:{int(sevkiyat_id)}'


def idempotency_tahsilat(tahsilat_kayit_id: int) -> str:
    return f'{BELGE_TIP_TAHSILAT}:{KAYNAK_TIP_TAHSILAT_KAYIT}:{int(tahsilat_kayit_id)}'


# Posting durumu (workflow durumundan AYRI — muhasebe yazım durumu)
POSTING_DURUM_BEKLIYOR = 'BEKLIYOR'
POSTING_DURUM_VALIDASYON_HATASI = 'VALIDASYON_HATASI'
POSTING_DURUM_HAZIR = 'HAZIR'
POSTING_DURUM_POST_EDILDI = 'POST_EDILDI'
POSTING_DURUM_BASARISIZ = 'BASARISIZ'

POSTING_DURUMLAR: tuple[str, ...] = (
    POSTING_DURUM_BEKLIYOR,
    POSTING_DURUM_VALIDASYON_HATASI,
    POSTING_DURUM_HAZIR,
    POSTING_DURUM_POST_EDILDI,
    POSTING_DURUM_BASARISIZ,
)

POSTING_DURUM_ETIKET = {
    POSTING_DURUM_BEKLIYOR: 'Posting Bekliyor',
    POSTING_DURUM_VALIDASYON_HATASI: 'Validasyon Hatası',
    POSTING_DURUM_HAZIR: 'Dry-Run Hazır',
    POSTING_DURUM_POST_EDILDI: 'Post Edildi',
    POSTING_DURUM_BASARISIZ: 'Posting Başarısız',
}


def posting_idempotency_key_uret(belge_idempotency_key: str) -> str:
    return f'POST:{belge_idempotency_key}'
