#Requires -Version 5.1
<#
.SYNOPSIS
  Start Araç GPS poll worker with bounded log rotation (10 MB x 5).

.PARAMETER PythonExe
  Exact path to real python.exe (WindowsApps alias rejected).

.PARAMETER ValidateOnly
  Preflight checks only — no worker start, no DB writes.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$PythonExe,

    [switch]$ValidateOnly
)

$ErrorActionPreference = 'Stop'

$Root = 'C:\Solariz_CPS_SERVER'
$AppDir = Join-Path $Root 'app'
$Worker = Join-Path $AppDir 'tools\arac_gps_poll_worker.py'
$LogDir = Join-Path $Root 'logs'
$OutLog = Join-Path $LogDir 'arac_gps_worker.out.log'
$ErrLog = Join-Path $LogDir 'arac_gps_worker.err.log'
$MaxLogBytes = 10MB
$MaxLogBackups = 5

function Test-WindowsAppsPythonAlias {
    param([string]$Path)
    $norm = ($Path -replace '\\', '/').ToLowerInvariant()
    return ($norm -match '/windowsapps/') -or ($norm -match '/microsoft/windowsapps/')
}

function Resolve-RealPythonExe {
    param([string]$Path)
    if ([string]::IsNullOrWhiteSpace($Path)) {
        throw 'PythonExe is required — PATH lookup and py launcher are not allowed.'
    }
    if (Test-WindowsAppsPythonAlias -Path $Path) {
        throw "WindowsApps python alias rejected: $Path"
    }
    $resolved = (Resolve-Path -LiteralPath $Path -ErrorAction Stop).Path
    if (-not (Test-Path -LiteralPath $resolved -PathType Leaf)) {
        throw "PythonExe is not a file: $resolved"
    }
    if ($resolved -match '\\WindowsApps\\') {
        throw "Resolved PythonExe is WindowsApps alias: $resolved"
    }
    return $resolved
}

function Test-PythonExeContract {
    param([string]$ResolvedPython)
    $probe = @"
import sys, os
sys.path.insert(0, r'$AppDir')
os.chdir(r'$AppDir')
expected = os.path.normcase(r'$ResolvedPython')
actual = os.path.normcase(sys.executable)
if expected != actual:
    raise SystemExit('sys.executable mismatch: ' + actual)
import modules.planlama.arac_gps_canonical_guard  # noqa: F401
import modules.planlama.arac_gps_poll_service  # noqa: F401
print('IMPORT_OK')
"@
    $tmp = Join-Path $env:TEMP ("arac_gps_py_probe_{0}.py" -f $PID)
    Set-Content -LiteralPath $tmp -Value $probe -Encoding UTF8
    try {
        $out = & $ResolvedPython $tmp 2>&1
        if ($LASTEXITCODE -ne 0 -or ($out -notmatch 'IMPORT_OK')) {
            throw "Python import smoke failed: $out"
        }
    }
    finally {
        Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue
    }
}

function Test-SchemaReadiness {
    param([string]$ResolvedPython)
    $probe = @"
import os, sqlite3, sys
sys.path.insert(0, r'$AppDir')
os.chdir(r'$AppDir')
db = os.path.join(r'$AppDir', 'mock_data.db')
con = sqlite3.connect(db, timeout=10)
try:
    integrity = con.execute('PRAGMA integrity_check').fetchone()[0]
    if integrity != 'ok':
        raise SystemExit('integrity=' + str(integrity))
    for t in ('arac_gps_snapshot', 'arac_plan_is_ziyaret_durum'):
        ok = con.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (t,)
        ).fetchone()
        if not ok:
            raise SystemExit('missing_table=' + t)
finally:
    con.close()
print('SCHEMA_OK')
"@
    $tmp = Join-Path $env:TEMP ("arac_gps_schema_probe_{0}.py" -f $PID)
    Set-Content -LiteralPath $tmp -Value $probe -Encoding UTF8
    try {
        $out = & $ResolvedPython $tmp 2>&1
        if ($LASTEXITCODE -ne 0 -or ($out -notmatch 'SCHEMA_OK')) {
            throw "Schema readiness failed: $out"
        }
    }
    finally {
        Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue
    }
}

function Test-FilomEnvPresence {
    $names = @('TURKCELL_FILOM_BASE_URL', 'TURKCELL_FILOM_USERNAME', 'TURKCELL_FILOM_PASSWORD')
    $found = @()
    foreach ($n in $names) {
        $u = [Environment]::GetEnvironmentVariable($n, 'User')
        $m = [Environment]::GetEnvironmentVariable($n, 'Machine')
        $p = [Environment]::GetEnvironmentVariable($n, 'Process')
        if ($u) { $found += "user:$n" }
        if ($m) { $found += "machine:$n" }
        if ($p) { $found += "process:$n" }
    }
    return $found
}

function New-LogSupervisorScript {
    param(
        [string]$ResolvedPython,
        [string]$WorkerPath,
        [string]$OutPath,
        [string]$ErrPath,
        [int]$MaxBytes,
        [int]$BackupCount
    )
    $supervisor = @"
# -*- coding: utf-8 -*-
"""Runtime GPS worker log supervisor — generated by Start-Arac-GPS-Worker.ps1"""
from __future__ import annotations

import logging
import logging.handlers
import os
import subprocess
import sys
import threading

WORKER = r'$WorkerPath'
PYTHON = r'$ResolvedPython'
OUT_LOG = r'$OutPath'
ERR_LOG = r'$ErrPath'
APP_DIR = r'$AppDir'
MAX_BYTES = $MaxBytes
BACKUP_COUNT = $BackupCount


def _handler(path: str) -> logging.Handler:
    os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
    h = logging.handlers.RotatingFileHandler(
        path, maxBytes=MAX_BYTES, backupCount=BACKUP_COUNT, encoding='utf-8',
    )
    h.setFormatter(logging.Formatter('%(message)s'))
    return h


def _pump(stream, logger: logging.Logger) -> None:
    for line in iter(stream.readline, ''):
        if not line:
            break
        logger.info(line.rstrip('\r\n'))
    stream.close()


def main() -> int:
    env = os.environ.copy()
    env['CPS_ARAC_GPS_CANONICAL_WRITE'] = 'YES'
    env['ARAC_GPS_POLL_INTERVAL_SEC'] = '60'
    env.pop('CPS_MOCK_DB_PATH', None)
    out_logger = logging.getLogger('gps_out')
    out_logger.setLevel(logging.INFO)
    out_logger.handlers.clear()
    out_logger.addHandler(_handler(OUT_LOG))
    err_logger = logging.getLogger('gps_err')
    err_logger.setLevel(logging.INFO)
    err_logger.handlers.clear()
    err_logger.addHandler(_handler(ERR_LOG))
    proc = subprocess.Popen(
        [PYTHON, '-u', WORKER],
        cwd=APP_DIR,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1,
    )
    t_out = threading.Thread(target=_pump, args=(proc.stdout, out_logger), daemon=True)
    t_err = threading.Thread(target=_pump, args=(proc.stderr, err_logger), daemon=True)
    t_out.start()
    t_err.start()
    return proc.wait()


if __name__ == '__main__':
    raise SystemExit(main())
"@
    $path = Join-Path $env:TEMP ("arac_gps_log_supervisor_{0}.py" -f $PID)
    Set-Content -LiteralPath $path -Value $supervisor -Encoding UTF8
    return $path
}

# --- Main ---
$resolvedPy = Resolve-RealPythonExe -Path $PythonExe

if (-not (Test-Path -LiteralPath $AppDir -PathType Container)) {
    throw "AppDir missing: $AppDir"
}
if (-not (Test-Path -LiteralPath $Worker -PathType Leaf)) {
    throw "Worker missing: $Worker"
}
New-Item -ItemType Directory -Force -Path $LogDir | Out-Null

Test-PythonExeContract -ResolvedPython $resolvedPy
Test-SchemaReadiness -ResolvedPython $resolvedPy

$filomSources = Test-FilomEnvPresence
$report = [ordered]@{
    PythonExe         = $resolvedPy
    AppDir            = $AppDir
    Worker            = $Worker
    OutLog            = $OutLog
    ErrLog            = $ErrLog
    MaxLogBytes       = $MaxLogBytes
    MaxLogBackups     = $MaxLogBackups
    CanonicalWrite    = 'YES (process scope via supervisor env)'
    PollIntervalSec   = 60
    MockDbPath        = 'unset'
    FilomEnvSources   = ($filomSources -join ', ')
    FilomEnvPresent   = ($filomSources.Count -ge 3)
}

foreach ($pair in $report.GetEnumerator()) {
    Write-Host ("VALIDATE {0}={1}" -f $pair.Key, $pair.Value)
}

if ($ValidateOnly) {
    Write-Host 'VALIDATE_ONLY=PASS'
    exit 0
}

if (-not $report.FilomEnvPresent) {
    Write-Warning 'Filom env vars not visible in User/Machine/Process scope — worker may fail fetch until vars are set for task principal.'
}

$supervisorPy = New-LogSupervisorScript -ResolvedPython $resolvedPy -WorkerPath $Worker `
    -OutPath $OutLog -ErrPath $ErrLog -MaxBytes $MaxLogBytes -BackupCount $MaxLogBackups

Write-Host "Starting GPS worker supervisor via $resolvedPy"
Write-Host "Supervisor: $supervisorPy"
& $resolvedPy $supervisorPy
exit $LASTEXITCODE
