# F2.1: Yeni endpoint /hedef/plan-darbogaz batch (v2 - triple-quote'suz)
import io, sys, shutil, time

PATH = r'C:\cps_dev\modules\hedef\routes.py'
MARKER = "@hedef_bp.route('/plan-darbogaz'"

with io.open(PATH, 'r', encoding='utf-8') as f:
    src = f.read()

if MARKER in src:
    print('SKIP: F2.1 zaten uygulanmis')
    sys.exit(0)

LINES = [
    "",
    "",
    "# === FAZ 4.8 F2.1: PLAN listesi icin batch darbogaz hesabi ===",
    "@hedef_bp.route('/plan-darbogaz', methods=['GET'])",
    "@hedef_yetkili",
    "def hedef_plan_darbogaz():",
    "    import sqlite3 as _sq_f21",
    "    from flask import jsonify, request",
    "    from modules.common import korgun as _kk_f21",
    "    from config import Config as _Cfg_f21",
    "    import re as _re_f21",
    "",
    "    raw = (request.args.get('emirler') or '').strip()",
    "    if not raw:",
    "        return jsonify({'ok': False, 'mesaj': 'emirler parametresi zorunlu'}), 400",
    "",
    "    if not _re_f21.match(r'^[0-9,\\s]+$', raw):",
    "        return jsonify({'ok': False, 'mesaj': 'gecersiz format'}), 400",
    "",
    "    parts = [p.strip() for p in raw.split(',') if p.strip()]",
    "    emirler = []",
    "    seen = set()",
    "    for p in parts:",
    "        if not p.isdigit():",
    "            continue",
    "        n = int(p)",
    "        if n <= 0 or n in seen:",
    "            continue",
    "        seen.add(n)",
    "        emirler.append(n)",
    "",
    "    if not emirler:",
    "        return jsonify({'ok': False, 'mesaj': 'gecerli emir yok'}), 400",
    "    if len(emirler) > 100:",
    "        return jsonify({'ok': False, 'mesaj': 'maksimum 100 emir'}), 400",
    "",
    "    sonuc = {}",
    "    alt_emir_map = {}",
    "    ana_proses_map = {}",
    "    hedef_map = {}",
    "    fis_map = {}",
    "    ana_model_map = {}",
    "",
    "    try:",
    "        kcon = _kk_f21._baglan()",
    "        try:",
    "            kcur = kcon.cursor()",
    "            ph1 = ','.join(['%s'] * len(emirler))",
    "",
    "            sql_alt = ('SELECT em2em.EmirNo, e.EmirNo, e.ModelKod, '",
    "                       'ISNULL(m.Tanim, e.ModelKod) '",
    "                       'FROM Urt_Em2Em em2em WITH (NOLOCK) '",
    "                       'INNER JOIN Urt_Emir e WITH (NOLOCK) ON e.EmirNo = em2em.EmirNo_YM '",
    "                       'LEFT JOIN Model_M m WITH (NOLOCK) ON m.ModelKod = e.ModelKod '",
    "                       'WHERE em2em.EmirNo IN (' + ph1 + ') '",
    "                       'AND UPPER(LTRIM(RTRIM(ISNULL(e.Tip,'+ chr(39) + chr(39) +')))) = '+ chr(39) + 'Y' + chr(39))",
    "            kcur.execute(sql_alt, tuple(emirler))",
    "            for r in kcur.fetchall():",
    "                ana_no = int(r[0])",
    "                alt_no = int(r[1])",
    "                mk = r[2] or ''",
    "                ma = r[3] or ''",
    "                kat = _alt_parca_kategori(mk, ma)",
    "                alt_emir_map.setdefault(ana_no, []).append({",
    "                    'alt_no': alt_no, 'model_kod': mk,",
    "                    'model_adi': ma, 'kategori': kat,",
    "                })",
    "",
    "            sql_ana = ('SELECT g.EmirNo, g.Proses, SUM(g.Cikan) '",
    "                       'FROM Urt_con_gch g WITH (NOLOCK) '",
    "                       'WHERE g.EmirNo IN (' + ph1 + ') AND g.Cikan > 0 '",
    "                       'GROUP BY g.EmirNo, g.Proses')",
    "            kcur.execute(sql_ana, tuple(emirler))",
    "            for r in kcur.fetchall():",
    "                ana_proses_map.setdefault(int(r[0]), []).append({",
    "                    'proses_kod': r[1],",
    "                    'yapilan': int(float(r[2] or 0)),",
    "                })",
    "",
    "            sql_fis = ('SELECT EmirNo, FisNo FROM Urt_Em_gch WITH (NOLOCK) '",
    "                       'WHERE EmirNo IN (' + ph1 + ') '",
    "                       'AND FisNo IS NOT NULL AND FisNo > 0 '",
    "                       'GROUP BY EmirNo, FisNo')",
    "            kcur.execute(sql_fis, tuple(emirler))",
    "            for r in kcur.fetchall():",
    "                fis_map.setdefault(int(r[0]), []).append(int(r[1]))",
    "",
    "            sql_mod = ('SELECT EmirNo, ModelKod FROM Urt_Emir WITH (NOLOCK) '",
    "                       'WHERE EmirNo IN (' + ph1 + ')')",
    "            kcur.execute(sql_mod, tuple(emirler))",
    "            for r in kcur.fetchall():",
    "                ana_model_map[int(r[0])] = r[1]",
    "",
    "            for ana in emirler:",
    "                model = ana_model_map.get(ana)",
    "                if not model:",
    "                    hedef_map[ana] = 0",
    "                    continue",
    "                fis_listesi = fis_map.get(ana, [])",
    "                if fis_listesi:",
    "                    ph_f = ','.join(['%s'] * len(fis_listesi))",
    "                    sql_h = ('SELECT COALESCE(SUM(Miktar), 0) FROM Siparis_Har WITH (NOLOCK) '",
    "                             'WHERE SKOD = %s AND SipNo IN (' + ph_f + ') '",
    "                             \"AND LTRIM(RTRIM(ISNULL(Durum,''))) = ''\")",
    "                    kcur.execute(sql_h, tuple([model] + fis_listesi))",
    "                else:",
    "                    sql_h = ('SELECT COALESCE(SUM(Miktar), 0) FROM Siparis_Har WITH (NOLOCK) '",
    "                             'WHERE SKOD = %s '",
    "                             \"AND LTRIM(RTRIM(ISNULL(Durum,''))) = ''\")",
    "                    kcur.execute(sql_h, (model,))",
    "                hedef_map[ana] = int(float(kcur.fetchone()[0] or 0))",
    "",
    "            kcur.close()",
    "        finally:",
    "            kcon.close()",
    "    except Exception as e_k:",
    "        return jsonify({",
    "            'ok': False,",
    "            'mesaj': 'Korgun erisim hatasi: ' + str(e_k)[:120]",
    "        }), 500",
    "",
    "    alt_son_proses = {}",
    "    alt_yapilan = {}",
    "    try:",
    "        ccon = _sq_f21.connect(_Cfg_f21.MOCK_DB_PATH)",
    "        try:",
    "            ccon.row_factory = _sq_f21.Row",
    "            tum_alt = []",
    "            for ana, alt_list in alt_emir_map.items():",
    "                for a in alt_list:",
    "                    tum_alt.append(str(a['alt_no']))",
    "            if tum_alt:",
    "                ph_a = ','.join(['?'] * len(tum_alt))",
    "                sql_son = ('SELECT emir_no, proses_adi FROM ('",
    "                           'SELECT emir_no, proses_adi, '",
    "                           'ROW_NUMBER() OVER (PARTITION BY emir_no '",
    "                           'ORDER BY siralama DESC, id DESC) AS rn '",
    "                           'FROM emir_alt_proses '",
    "                           'WHERE emir_no IN (' + ph_a + ') AND aktif = 1'",
    "                           ') WHERE rn = 1')",
    "                rows = ccon.execute(sql_son, tuple(tum_alt)).fetchall()",
    "                for r in rows:",
    "                    alt_son_proses[str(r['emir_no'])] = r['proses_adi']",
    "",
    "                sql_yp = ('SELECT CAST(emir_no AS TEXT) AS en, '",
    "                          'LOWER(TRIM(proses_adi)) AS pa, '",
    "                          'COALESCE(SUM(miktar), 0) AS yp '",
    "                          'FROM uretim_kayit '",
    "                          'WHERE CAST(emir_no AS TEXT) IN (' + ph_a + ') '",
    "                          \"AND onay_durum IN ('onaylandi','bekliyor') \"",
    "                          'GROUP BY CAST(emir_no AS TEXT), LOWER(TRIM(proses_adi))')",
    "                rows2 = ccon.execute(sql_yp, tuple(tum_alt)).fetchall()",
    "                for r in rows2:",
    "                    alt_yapilan[(r['en'], r['pa'])] = int(r['yp'] or 0)",
    "        finally:",
    "            ccon.close()",
    "    except Exception as e_s:",
    "        return jsonify({",
    "            'ok': False,",
    "            'mesaj': 'CPS DB hatasi: ' + str(e_s)[:120]",
    "        }), 500",
    "",
    "    for ana in emirler:",
    "        try:",
    "            hedef = hedef_map.get(ana, 0)",
    "            alt_list = alt_emir_map.get(ana, [])",
    "            atki_t = 0",
    "            atki_var = False",
    "            govde_t = 0",
    "            govde_var = False",
    "            for a in alt_list:",
    "                kat_lower = (a.get('kategori') or '').lower()",
    "                alt_str = str(a['alt_no'])",
    "                son_p = alt_son_proses.get(alt_str)",
    "                if son_p:",
    "                    yp = alt_yapilan.get((alt_str, son_p.strip().lower()), 0)",
    "                else:",
    "                    yp = 0",
    "                if kat_lower in ('atki', 'atk\\u0131'):",
    "                    atki_var = True",
    "                    atki_t = yp",
    "                elif kat_lower in ('govde', 'g\\u00f6vde'):",
    "                    govde_var = True",
    "                    govde_t = yp",
    "",
    "            mamul_son = alt_son_proses.get(str(ana))",
    "            if mamul_son:",
    "                mamul_t = alt_yapilan.get((str(ana), mamul_son.strip().lower()), 0)",
    "            else:",
    "                ana_prs = ana_proses_map.get(ana, [])",
    "                if ana_prs:",
    "                    def _kod_int(p):",
    "                        k = str(p.get('proses_kod') or '')",
    "                        return int(k) if k.isdigit() else -1",
    "                    en_son = max(ana_prs, key=_kod_int)",
    "                    if _kod_int(en_son) >= 0:",
    "                        mamul_t = int(en_son.get('yapilan') or 0)",
    "                    else:",
    "                        mamul_t = 0",
    "                else:",
    "                    mamul_t = 0",
    "",
    "            adaylar = [('MAMUL', mamul_t)]",
    "            if atki_var:",
    "                adaylar.append(('ATKI', atki_t))",
    "            if govde_var:",
    "                adaylar.append(('GOVDE', govde_t))",
    "            en_dusuk = min(adaylar, key=lambda x: x[1])",
    "",
    "            yapilan_d = int(en_dusuk[1])",
    "            darbogaz_kat = en_dusuk[0]",
    "            kalan_d = max(0, hedef - yapilan_d)",
    "            yuzde_d = round((yapilan_d / hedef * 100), 1) if hedef > 0 else 0.0",
    "",
    "            sonuc[str(ana)] = {",
    "                'yapilan_darbogaz': yapilan_d,",
    "                'kalan_darbogaz': kalan_d,",
    "                'yuzde_darbogaz': yuzde_d,",
    "                'darbogaz_kategori': darbogaz_kat,",
    "                'hedef': hedef,",
    "            }",
    "        except Exception as e_loop:",
    "            sonuc[str(ana)] = {",
    "                'yapilan_darbogaz': None,",
    "                'kalan_darbogaz': None,",
    "                'yuzde_darbogaz': None,",
    "                'darbogaz_kategori': None,",
    "                'hedef': None,",
    "                'hata': str(e_loop)[:80],",
    "            }",
    "",
    "    return jsonify({",
    "        'ok': True,",
    "        'darbogaz': sonuc,",
    "        'emir_sayisi': len(emirler),",
    "    })",
    "# === /FAZ 4.8 F2.1 ===",
    "",
]

ENDPOINT = '\n'.join(LINES)
new_src = src.rstrip() + '\n' + ENDPOINT

bak = PATH + '.bak_pre_f21_' + time.strftime('%Y%m%d_%H%M%S')
shutil.copy2(PATH, bak)
print('Yedek: ' + bak)

with io.open(PATH, 'w', encoding='utf-8') as f:
    f.write(new_src)

artis = len(new_src) - len(src)
print('OK: F2.1 endpoint eklendi (' + str(artis) + ' byte)')
print('Test: http://localhost:5057/hedef/plan-darbogaz?emirler=110626')