# F2.2: PLAN tablosu darbogaz lazy load - hedef.js sonuna IIFE
import io, sys, shutil, time

JS_PATH = r'C:\cps_dev\static\js\hedef.js'
MARKER = '_planDarbogazF22Yuklendi'

with io.open(JS_PATH, 'r', encoding='utf-8') as f:
    src = f.read()

if MARKER in src:
    print('SKIP: F2.2 zaten uygulanmis')
    sys.exit(0)

LINES = [
    '',
    '',
    '/* === FAZ 4.8 F2.2: PLAN tablosu darbogaz lazy load === */',
    '(function () {',
    '    if (window._planDarbogazF22Yuklendi) return;',
    '    window._planDarbogazF22Yuklendi = true;',
    '',
    '    function _f22Fmt(n) {',
    '        if (n === null || n === undefined || n === "") return "0";',
    '        var x = Number(n);',
    '        if (!isFinite(x)) return "0";',
    '        return Math.round(x).toLocaleString("tr-TR");',
    '    }',
    '',
    '    function _f22FmtPct(n) {',
    '        if (n === null || n === undefined) return "0%";',
    '        var x = Number(n);',
    '        if (!isFinite(x)) return "0%";',
    '        return x.toLocaleString("tr-TR", { maximumFractionDigits: 1 }) + "%";',
    '    }',
    '',
    '    /* Header text ile sutun indeksini bul */',
    '    function _f22SutunIndeksleri(table) {',
    '        var thead = table.querySelector("thead tr");',
    '        if (!thead) return null;',
    '        var ths = thead.querySelectorAll("th");',
    '        var idx = { yapilan: -1, kalan: -1, yuzde: -1, emir: -1 };',
    '        for (var i = 0; i < ths.length; i++) {',
    '            var t = (ths[i].textContent || "").trim().toUpperCase();',
    '            if (t === "YAPILAN") idx.yapilan = i;',
    '            else if (t === "KALAN") idx.kalan = i;',
    '            else if (t === "%") idx.yuzde = i;',
    '            else if (t === "EMIR" || t === "EMİR") idx.emir = i;',
    '        }',
    '        return idx;',
    '    }',
    '',
    '    /* Bir TR icindeki emir_no\'yu cikart */',
    '    function _f22EmirNoBul(tr, emirIdx) {',
    '        var v = tr.getAttribute("data-emir-no") || tr.getAttribute("data-emir");',
    '        if (v) {',
    '            var d = String(v).replace(/\\D/g, "");',
    '            if (d) return d;',
    '        }',
    '        if (emirIdx >= 0) {',
    '            var cells = tr.querySelectorAll("td");',
    '            if (cells.length > emirIdx) {',
    '                var t = (cells[emirIdx].textContent || "").replace(/\\D/g, "");',
    '                if (t) return t;',
    '            }',
    '        }',
    '        return null;',
    '    }',
    '',
    '    /* PLAN tablosunu bul ve darbogaz cek */',
    '    function _f22Calistir() {',
    '        var planBody = document.getElementById("planBody");',
    '        if (!planBody) return;',
    '        var table = planBody.closest("table");',
    '        if (!table) return;',
    '',
    '        var idx = _f22SutunIndeksleri(table);',
    '        if (!idx) return;',
    '        if (idx.yapilan < 0 && idx.kalan < 0 && idx.yuzde < 0) return;',
    '',
    '        /* Detay satirlarini ATLA, sadece ana data satirlari */',
    '        var rows = planBody.querySelectorAll("tr");',
    '        var emirToTr = {};',
    '        var emirler = [];',
    '        for (var i = 0; i < rows.length; i++) {',
    '            var tr = rows[i];',
    '            if (tr.classList.contains("plan-detay-mini")) continue;',
    '            if (tr.classList.contains("plan-detay-row")) continue;',
    '            var en = _f22EmirNoBul(tr, idx.emir);',
    '            if (!en) continue;',
    '            if (!emirToTr[en]) {',
    '                emirToTr[en] = tr;',
    '                emirler.push(en);',
    '            }',
    '        }',
    '',
    '        if (emirler.length === 0) return;',
    '        if (emirler.length > 100) emirler = emirler.slice(0, 100);',
    '',
    '        var url = "/hedef/plan-darbogaz?emirler=" + encodeURIComponent(emirler.join(","));',
    '        fetch(url, {',
    '            credentials: "same-origin",',
    '            headers: { "Accept": "application/json" }',
    '        }).then(function (r) {',
    '            if (!r.ok) throw new Error("HTTP " + r.status);',
    '            return r.json();',
    '        }).then(function (data) {',
    '            if (!data || !data.ok || !data.darbogaz) return; /* sessiz fallback */',
    '            var d = data.darbogaz;',
    '            for (var k in d) {',
    '                if (!Object.prototype.hasOwnProperty.call(d, k)) continue;',
    '                var tr2 = emirToTr[k];',
    '                if (!tr2) continue;',
    '                var v = d[k];',
    '                if (!v) continue;',
    '                if (v.yapilan_darbogaz === null || v.yapilan_darbogaz === undefined) continue;',
    '                var cells = tr2.querySelectorAll("td");',
    '                if (idx.yapilan >= 0 && cells.length > idx.yapilan) {',
    '                    cells[idx.yapilan].textContent = _f22Fmt(v.yapilan_darbogaz);',
    '                }',
    '                if (idx.kalan >= 0 && cells.length > idx.kalan) {',
    '                    cells[idx.kalan].textContent = _f22Fmt(v.kalan_darbogaz);',
    '                }',
    '                if (idx.yuzde >= 0 && cells.length > idx.yuzde) {',
    '                    /* Yuzde hucresi pill icerebilir, varsa onun textContent\'ini guncelle */',
    '                    var yc = cells[idx.yuzde];',
    '                    var pill = yc.querySelector(".pill, .badge, span");',
    '                    if (pill) {',
    '                        pill.textContent = _f22FmtPct(v.yuzde_darbogaz);',
    '                    } else {',
    '                        yc.textContent = _f22FmtPct(v.yuzde_darbogaz);',
    '                    }',
    '                }',
    '            }',
    '        }).catch(function (err) {',
    '            /* Sessiz fallback - eski degerler kalir */',
    '            try { console.warn("[F2.2] darbogaz fetch hata:", err); } catch (e) {}',
    '        });',
    '    }',
    '',
    '    /* PLAN tablosu render edildikten sonra calis. */',
    '    /* renderPlanRows mevcut JS\'de override edilmis (V3/V4 IIFE). En son override\'in ustune sarmalayalim. */',
    '    function _f22Sar() {',
    '        if (typeof window.renderPlanRows === "function" && !window._origRenderRowsF22) {',
    '            window._origRenderRowsF22 = window.renderPlanRows;',
    '            window.renderPlanRows = function (emirler) {',
    '                var sonuc = window._origRenderRowsF22.apply(this, arguments);',
    '                /* Render bittikten sonra darbogaz cek */',
    '                setTimeout(_f22Calistir, 50);',
    '                return sonuc;',
    '            };',
    '        }',
    '    }',
    '',
    '    /* DOMContentLoaded sonrasi sarma */',
    '    if (document.readyState === "loading") {',
    '        document.addEventListener("DOMContentLoaded", function () {',
    '            _f22Sar();',
    '            /* Tablo zaten doluysa hemen calistir */',
    '            setTimeout(_f22Calistir, 100);',
    '        });',
    '    } else {',
    '        _f22Sar();',
    '        setTimeout(_f22Calistir, 100);',
    '    }',
    '',
    '    console.log("[CPS LOCAL] PLAN darbogaz F2.2 yuklendi");',
    '})();',
    '/* === /FAZ 4.8 F2.2 === */',
    '',
]

ADD = '\n'.join(LINES)
new_src = src.rstrip() + '\n' + ADD

bak = JS_PATH + '.bak_pre_f22_' + time.strftime('%Y%m%d_%H%M%S')
shutil.copy2(JS_PATH, bak)
print('Yedek: ' + bak)

with io.open(JS_PATH, 'w', encoding='utf-8') as f:
    f.write(new_src)

artis = len(new_src) - len(src)
print('OK: F2.2 IIFE eklendi (' + str(artis) + ' byte)')
print('Test: PLAN sekmesi -> Ctrl+F5 -> YAPILAN/KALAN/% darbogaz degerleri')